
// Generated by https://quicktype.io

export class Campaign {
    name:         string;
    title:        string;
    description:  string;
    url:          string;
    idOnPlatform: string;
    image : string
}


export class CrawlCampaign {
    email:        string;
    url:          string;
   
}


export class Page{
    page :      string;
}


export class CampaignPermisson {
    id:           number;
    userId:       number;
    idOnPlatform: string;
    name:         string;
    status:       number;
    title:        string;
    description:  string;
    url:          string;
    totalRaised:  number;
    platformId:   number;
    email:        string;
}



